Use container to build artifacts (#75)
### Why?

Ubuntu 24.04 uses `glibc 2.39` while we want to keep using `glibc 2.29`
as before when compiling the native code.

### What changed?

- Use `ubuntu:20.04` docker image for building and testing step
- Update the cgroup test to support both cgroup v1 and cgroup v2 because
Ubuntu 20.04 uses v1 but still want to keep the ability to run the tests
on a system with v2

---------

Co-authored-by: lhchavez <lhchavez@lhchavez.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -21,21 +21,32 @@ permissions:
   pull_request: null
 
 jobs:
-  build-test:
+  build:
     strategy:
       fail-fast: false
       matrix:
         settings:
           - host: macos-14-large
             target: x86_64-apple-darwin
+            description: "macOS 14"
           - host: macos-latest
             target: aarch64-apple-darwin
+            description: "macOS latest"
           - host: ubuntu-24.04
             target: x86_64-unknown-linux-gnu
-    name: Build and test on ${{ matrix.settings.target }}
+            container: ubuntu:20.04
+            description: "Ubuntu Container(20.04)"
+    name: Build ${{ matrix.settings.target }} on (${{ matrix.settings.description }})
     runs-on: ${{ matrix.settings.host }}
+    container:
+      image: ${{ matrix.settings.host == 'ubuntu-24.04' && matrix.settings.container || '' }}
     steps:
       - uses: actions/checkout@v4
+      - name: Install container dependencies
+        if: matrix.settings.host == 'ubuntu-24.04'
+        run: |
+          apt-get update
+          apt-get install -y curl build-essential
       - name: Setup node
         uses: actions/setup-node@v4
         with:
@@ -64,9 +75,20 @@ jobs:
           strip -x *.node
         shell: bash
       - name: Dump GLIBC symbols
-        run: objdump -T *.node | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu
-      - name: Test bindings
-        run: npm run test:ci
+        if: matrix.settings.host == 'ubuntu-24.04'
+        run: |
+          objdump -T *.node | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu > glibc_versions.txt
+          
+          if [ -s glibc_versions.txt ]; then
+            MAX_VERSION=$(cat glibc_versions.txt | sort -V | tail -n 1)
+            echo "Highest GLIBC version: $MAX_VERSION"
+            
+            if [ "$(echo "$MAX_VERSION 2.29" | awk '{if ($1 > $2) print "1"; else print "0"}')" -eq 1 ]; then
+              echo "Error: GLIBC version $MAX_VERSION is larger than 2.29"
+              exit 1
+            fi
+          fi
+        shell: bash
       - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
@@ -74,12 +96,68 @@ jobs:
           path: ${{ env.APP_NAME }}.*.node
           if-no-files-found: error
 
+  test:
+    needs: build
+    strategy:
+      fail-fast: false
+      matrix:
+        settings:
+          - host: macos-14-large
+            target: x86_64-apple-darwin
+            description: "macOS 14"
+          - host: macos-latest
+            target: aarch64-apple-darwin
+            description: "macOS latest"
+          - host: ubuntu-24.04
+            target: x86_64-unknown-linux-gnu
+            container: ubuntu:20.04
+            description: "Ubuntu Container(20.04)"
+          - host: ubuntu-24.04
+            target: x86_64-unknown-linux-gnu
+            container: ubuntu:24.04
+            description: "Ubuntu Container(24.04)"
+    name: Test on ${{ matrix.settings.target }} (${{ matrix.settings.description }})
+    runs-on: ${{ matrix.settings.host }}
+    container: 
+      image: ${{ matrix.settings.host == 'ubuntu-24.04' && matrix.settings.container || '' }}
+      options: --privileged
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install container dependencies
+        if: matrix.settings.host == 'ubuntu-24.04'
+        run: |
+          apt-get update
+          apt-get install -y curl build-essential sudo cgroup-tools coreutils
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+      - name: Install dependencies
+        run: npm ci
+      - name: Download build artifacts
+        # Special case for Ubuntu 24.04 - reuse the 20.04 artifacts
+        if: matrix.settings.container == 'ubuntu:24.04'
+        uses: actions/download-artifact@v4
+        with:
+          name: bindings-x86_64-unknown-linux-gnu
+
+      - name: Download build artifacts
+        # For all other platforms - use the matching bindings
+        if: matrix.settings.container != 'ubuntu:24.04'
+        uses: actions/download-artifact@v4
+        with:
+          name: bindings-${{ matrix.settings.target }}
+      
+      - name: Test bindings
+        run: npm run test:ci
+
   publish:
     name: Publish
     runs-on: ubuntu-24.04
+    container: ubuntu:20.04
     if: github.ref == 'refs/heads/main'
     needs:
-      - build-test
+      - test
     steps:
       - uses: actions/checkout@v4
       - name: Setup node
