Use container to build artifacts

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -32,8 +32,10 @@ jobs:
             target: aarch64-apple-darwin
           - host: ubuntu-24.04
             target: x86_64-unknown-linux-gnu
+            container: ubuntu:20.04
     name: Build and test on ${{ matrix.settings.target }}
     runs-on: ${{ matrix.settings.host }}
+    container: ${{ matrix.settings.host == 'ubuntu-24.04' && matrix.settings.container || '' }}
     steps:
       - uses: actions/checkout@v4
       - name: Setup node
@@ -64,7 +66,19 @@ jobs:
           strip -x *.node
         shell: bash
       - name: Dump GLIBC symbols
-        run: objdump -T *.node | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu
+        run: |
+          objdump -T *.node | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu > glibc_versions.txt
+          
+          if [ -s glibc_versions.txt ]; then
+            MAX_VERSION=$(cat glibc_versions.txt | sort -V | tail -n 1)
+            echo "Highest GLIBC version: $MAX_VERSION"
+            
+            if [ "$(echo "$MAX_VERSION 2.29" | awk '{if ($1 > $2) print "1"; else print "0"}')" -eq 1 ]; then
+              echo "Error: GLIBC version $MAX_VERSION is larger than 2.29"
+              exit 1
+            fi
+          fi
+        shell: bash
       - name: Test bindings
         run: npm run test:ci
       - name: Upload artifact
@@ -77,6 +91,7 @@ jobs:
   publish:
     name: Publish
     runs-on: ubuntu-24.04
+    container: ubuntu:20.04
     if: github.ref == 'refs/heads/main'
     needs:
       - build-test
